drop table if exists tb_user;
create table tb_user
(
    id         UUID         not null primary key,
    email      varchar(255) not null unique,
    password   varchar(255) not null,
    created_at timestamp,
    updated_at timestamp,
    last_login timestamp
);


drop table if exists tb_role;
create table tb_role
(
    id          UUID        not null primary key,
    name        varchar(50) not null unique,
    description varchar(255),
    created_at  timestamp,
    updated_at  timestamp
);


drop table if exists tb_mm_user_role;
create table tb_mm_user_role
(
    id          bigint generated by default as identity not null primary key,
    user_id     UUID                                    not null
        constraint fk_tb_mm_user_role_tb_user_id
            references tb_user,
    role_id     UUID                                    not null
        constraint fk_tb_mm_user_role_tb_role_id
            references tb_role,
    assigned_at timestamp
);